import { Pokemon } from './types';

export const POKEMON_STARTERS: Pokemon[] = [
  {
    id: 1,
    name: '喷火龙',
    type: '火',
    maxHp: 150,
    currentHp: 150,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',
    color: 'bg-orange-500',
    moves: [
      { name: '喷射火焰', type: '火', power: 90 },
      { name: '龙爪', type: '龙', power: 80 },
      { name: '空气斩', type: '飞行', power: 75 },
      { name: '大字爆炎', type: '火', power: 110 },
    ],
  },
  {
    id: 2,
    name: '妙蛙花',
    type: '草',
    maxHp: 160,
    currentHp: 160,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png',
    color: 'bg-green-600',
    moves: [
      { name: '能量球', type: '草', power: 90 },
      { name: '污泥炸弹', type: '毒', power: 90 },
      { name: '地震', type: '地面', power: 100 },
      { name: '疯狂植物', type: '草', power: 120 },
    ],
  },
  {
    id: 3,
    name: '水箭龟',
    type: '水',
    maxHp: 170,
    currentHp: 170,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png',
    color: 'bg-blue-500',
    moves: [
      { name: '水炮', type: '水', power: 110 },
      { name: '加农光炮', type: '钢', power: 80 },
      { name: '冰冻光束', type: '冰', power: 90 },
      { name: '咬碎', type: '恶', power: 80 },
    ],
  },
];

export const ENEMIES: Pokemon[] = [
  {
    id: 4,
    name: '皮卡丘',
    type: '电',
    maxHp: 120,
    currentHp: 120,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
    color: 'bg-yellow-400',
    moves: [{ name: '十万伏特', type: '电', power: 90 }],
  },
  {
    id: 5,
    name: '耿鬼',
    type: '幽灵',
    maxHp: 135,
    currentHp: 135,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/94.png',
    color: 'bg-purple-600',
    moves: [{ name: '暗影球', type: '幽灵', power: 80 }],
  },
  {
    id: 6,
    name: '超梦',
    type: '超能力',
    maxHp: 180,
    currentHp: 180,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/150.png',
    color: 'bg-purple-400',
    moves: [{ name: '精神击破', type: '超能力', power: 100 }],
  },
  {
    id: 7,
    name: '甲贺忍蛙',
    type: '水',
    maxHp: 130,
    currentHp: 130,
    spriteFront: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/658.png',
    spriteBack: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/658.png',
    color: 'bg-blue-700',
    moves: [{ name: '飞水手里剑', type: '水', power: 90 }],
  },
];